name: Deploy to cPanel

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Upload to temp
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.CPANEL_HOST }}
          username: ${{ secrets.CPANEL_USERNAME }}
          key: ${{ secrets.CPANEL_SSH_KEY }}
          port: ${{ secrets.CPANEL_PORT }}
          source: "./*"
          target: "/home2/${{ secrets.CPANEL_USERNAME }}/deploy-temp"

      - name: Move files
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ secrets.CPANEL_HOST }}
          username: ${{ secrets.CPANEL_USERNAME }}
          key: ${{ secrets.CPANEL_SSH_KEY }}
          port: ${{ secrets.CPANEL_PORT }}
          script: |
            mkdir -p /home2/${{ secrets.CPANEL_USERNAME }}/icravivalista.com.br
            cp -r /home2/${{ secrets.CPANEL_USERNAME }}/deploy-temp/* /home2/${{ secrets.CPANEL_USERNAME }}/icravivalista.com.br/
