name: Debug cPanel SSH

on:
  workflow_dispatch:

jobs:
  debug:
    runs-on: ubuntu-latest

    steps:
      - name: Test SSH connection
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ secrets.CPANEL_HOST }}
          username: ${{ secrets.CPANEL_USERNAME }}
          key: ${{ secrets.CPANEL_SSH_KEY }}
          port: ${{ secrets.CPANEL_PORT }}
          script: |
            echo "USER: $(whoami)"
            echo "HOME: $HOME"
            pwd
            uname -a
            ls -la /home2/${{ secrets.CPANEL_USERNAME }}
            ls -la /home2/${{ secrets.CPANEL_USERNAME }}/public_html
